# Generated by Django 4.2.7 on 2025-07-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='name_uz',
        ),
    ]
