# Generated by Django 4.2.7 on 2025-10-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='udk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Universal Decimal Classification'),
        ),
    ]
