# Generated by Django 4.2.7 on 2025-07-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(choices=[('AI_Gemini', 'AI Gemini'), ('PlagiarismChecker', 'Plagiarism Checker'), ('DOI_Provider', 'DOI Provider')], max_length=50, unique=True)),
                ('isEnabled', models.BooleanField(default=False)),
                ('apiKey', models.CharField(blank=True, max_length=255)),
                ('monthlyLimit', models.PositiveIntegerField(blank=True, null=True)),
                ('serviceUrl', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
