# Generated by Django 4.2.7 on 2025-09-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicktransaction',
            name='click_trans_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='CLICK Trans ID'),
        ),
    ]
