# Generated by Django 4.2.7 on 2025-10-28 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_udk'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='assigned_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_udc_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='udc_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UDC Code'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('udc_assigned', 'UDC Assigned')], default='pending_payment', max_length=20),
        ),
    ]
