# Generated by Django 4.2.7 on 2025-10-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_serviceorder_assigned_writer_serviceorder_udc_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='printing_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Printing Status'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Shipped Date'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tracking Number'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('udc_assigned', 'UDC Assigned'), ('printing', 'Printing'), ('shipped', 'Shipped')], default='pending_payment', max_length=20),
        ),
    ]
