# Generated by Django 4.2.7 on 2025-10-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_service_serviceorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='submissionReceiptFile',
        ),
        migrations.AlterField(
            model_name='article',
            name='submissionPaymentStatus',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed')], default='payment_pending', max_length=50),
        ),
    ]
