# Generated by Django 4.2.7 on 2025-10-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_serviceorder_printing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='calculated_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Calculated Price'),
        ),
    ]
